### ISSUE TITLE
Broken with dream update #2

### ISSUE THREAD

**Issue by TonyGermaneri** [Alesseon/ONI-BottlesToPipes#20]
Hello @Alesseon!

Seems I can't load a save games while using your wonderful mod. Guessing this is still related to the update, but what do I know. I've attached the stack trace from the mod info screen.

Thanks for the mod! Hope the trace help!

Thanks,
Tony
```

Error in Alesseon.LiquidBottleEmptierComplete.LiquidBottleEmptier.OnSpawn 
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingFieldException: Field 'TreeFilterable.OnFilterChanged' not found.
  at (wrapper managed-to-native) System.Reflection.MonoCMethod.InternalInvoke(System.Reflection.MonoCMethod,object,object[],System.Exception&)
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00002] in <695d1cc93cca45069c528c15c9fdd749>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00014] in <695d1cc93cca45069c528c15c9fdd749>:0 
  at System.Reflection.MonoCMethod.DoInvoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0007a] in <695d1cc93cca45069c528c15c9fdd749>:0 
  at System.Reflection.MonoCMethod.Invoke (System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <695d1cc93cca45069c528c15c9fdd749>:0 
  at System.RuntimeType.CreateInstanceImpl (System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes, System.Threading.StackCrawlMark& stackMark) [0x00213] in <695d1cc93cca45069c528c15c9fdd749>:0 
  at System.Activator.CreateInstance (System.Type type, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes) [0x00095] in <695d1cc93cca45069c528c15c9fdd749>:0 
  at System.Activator.CreateInstance (System.Type type, System.Object[] args) [0x00000] in <695d1cc93cca45069c528c15c9fdd749>:0 
  at StateMachineComponent`1[StateMachineInstanceType].get_smi () [0x0000d] in <cb20703507b14eea8088dbc44abf7f85>:0 
  at Alesseon.LiquidBottler.Building.LiquidBottleEmptier.OnSpawn () [0x00006] in <5ee85d679aaf4b78b2b8c9533c52a741>:0 
  at KMonoBehaviour.Spawn () [0x0005d] in <1b5c2ff4f53d4a48b7159ed84d905978>:0 

  at UnityEngine.Debug.LogError (System.Object message, UnityEngine.Object context) [0x00000] in <72b60a3dd8cd4f12a155b761a1af9144>:0 
  at Debug.LogError (System.Object obj, UnityEngine.Object context) [0x00000] in <1b5c2ff4f53d4a48b7159ed84d905978>:0 
  at DebugUtil.LogErrorArgs (UnityEngine.Object context, System.Object[] objs) [0x00000] in <1b5c2ff4f53d4a48b7159ed84d905978>:0 
  at DebugUtil.LogException (UnityEngine.Object context, System.String errorMessage, System.Exception e) [0x00000] in <1b5c2ff4f53d4a48b7159ed84d905978>:0 
  at KMonoBehaviour.Spawn () [0x00000] in <1b5c2ff4f53d4a48b7159ed84d905978>:0 
  at KMonoBehaviour.Start () [0x00000] in <1b5c2ff4f53d4a48b7159ed84d905978>:0 
Build: U43-526233-S
```

**Comment by vitvavra** [comment]
Hi, can you re-verify that your mod version is really 526233? There is some delay between the upload and when steam really distributes the mod, so you might not see any updates but you would not have the latest version.

I am not able to reproduce the issue in any way, and the issue appears to be the same as in the version i just fixed.

**Comment by TonyGermaneri** [comment]
Hello again!  I'm not sure where to see the version.  I am using the version published Update: Oct 7 @ 12:20pm.  There seems to be others that can reproduce the error in the workshop comments.  If I have the old version here maybe the old version was published Oct 7?

Thanks for all the help!  Great mod!

To reproduce the error I did the following:
* Unsubscribe from workshop
* Start ONI
* Ensure mod is not in the list
* Quit ONI
* Subscribe to mod
* Start ONI
* Enable mod
* Start new game in sandbox
* Add Liquid Bottle Emptier
* CRASH!

```Error in Alesseon.LiquidBottleEmptierComplete.LiquidBottleEmptier.OnSpawn 
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingFieldException: Field 'TreeFilterable.OnFilterChanged' not found.
  at (wrapper managed-to-native) System.Reflection.MonoCMethod.InternalInvoke(System.Reflection.MonoCMethod,object,object[],System.Exception&)
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00002] in <695d1cc93cca45069c528c15c9fdd749>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00014] in <695d1cc93cca45069c528c15c9fdd749>:0 
  at System.Reflection.MonoCMethod.DoInvoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0007a] in <695d1cc93cca45069c528c15c9fdd749>:0 
  at System.Reflection.MonoCMethod.Invoke (System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <695d1cc93cca45069c528c15c9fdd749>:0 
  at System.RuntimeType.CreateInstanceImpl (System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes, System.Threading.StackCrawlMark& stackMark) [0x00213] in <695d1cc93cca45069c528c15c9fdd749>:0 
  at System.Activator.CreateInstance (System.Type type, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes) [0x00095] in <695d1cc93cca45069c528c15c9fdd749>:0 
  at System.Activator.CreateInstance (System.Type type, System.Object[] args) [0x00000] in <695d1cc93cca45069c528c15c9fdd749>:0 
  at StateMachineComponent`1[StateMachineInstanceType].get_smi () [0x0000d] in <322ab64cfe564736a3a4cd0cabcbbf3c>:0 
  at Alesseon.LiquidBottler.Building.LiquidBottleEmptier.OnSpawn () [0x00006] in <5ee85d679aaf4b78b2b8c9533c52a741>:0 
  at KMonoBehaviour.Spawn () [0x0005d] in <1b5c2ff4f53d4a48b7159ed84d905978>:0 

  at UnityEngine.Debug.LogError (System.Object message, UnityEngine.Object context) [0x00000] in <72b60a3dd8cd4f12a155b761a1af9144>:0 
  at Debug.LogError (System.Object obj, UnityEngine.Object context) [0x00000] in <1b5c2ff4f53d4a48b7159ed84d905978>:0 
  at DebugUtil.LogErrorArgs (UnityEngine.Object context, System.Object[] objs) [0x00000] in <1b5c2ff4f53d4a48b7159ed84d905978>:0 
  at DebugUtil.LogException (UnityEngine.Object context, System.String errorMessage, System.Exception e) [0x00000] in <1b5c2ff4f53d4a48b7159ed84d905978>:0 
  at KMonoBehaviour.Spawn () [0x00000] in <1b5c2ff4f53d4a48b7159ed84d905978>:0 
  at KMonoBehaviour.Start () [0x00000] in <1b5c2ff4f53d4a48b7159ed84d905978>:0 
Build: U43-526946-S

**Comment by jaypha** [comment]
Hi.
I had a similar problem. It showed the 'v526233' in the mod manager, but when i looked at the actual files, I noticed that the old version was still there. I deleted the files, unsubbed, resubbed, got the mod manager to force update the mod, and was pleased to find that the problem was resolved.
@TonyGermaneri , try having a look at the actual files that are installed for the mod and check if they are indeed the latest version.
Thanks for the mod, and the fix @Alesseon.

**Comment by vitvavra** [comment]
I am returning wit some news, i can safely reproduce the steps using @TonyGermaneri  instructions. I tried to re-upload the mod with deleted previous archived version and see if it helps.

**Comment by TonyGermaneri** [comment]
Thanks for the advice @jaypha.  I've tried just about everything to get it to work with no luck.  I've tried deleting the files manually, restarting, resubscribing, watching the new files come in, loading up a brand new game, adding the item, and it crashes.  I see version 1.5.0 in the mod's yaml file.  mods.json says it's version 1668677543.  This is now for the version released 2 days ago.

**Comment by vitvavra** [comment]
I tried to re-compile it, also removed every archived  version there is in case there is an issue with that, and re-uploaded again. As long as this does not work, i do not have any solution as of now.

**Comment by vitvavra** [comment]
@TonyGermaneri Could you verify that the issue still persist?
